FRED-262: added guild id field in the token grant
game-tv/reactor-oauth pull request #1
Opened 2022-08-30 11:13 UTC by kanishkdebnath-bst

added support to get guild id from token grant

2022-09-06 11:45 UTC, freyacodes requested changes

2022-09-06 11:45 UTC, freyacodes commented on src/main/kotlin/gg/botlabs/oauth/OAuthApplication.kt
> +                    getJSONObject("guild").optString("id")
Reactor-oauth is a generic OAuth2 client, not a Discord library. Instead you should pass the token grant JSONObject (`this`), such that arbitrary data from the code grant can be accessed instead.

Besides, `getJSONObject("guild")` will throw an exception any time a code grant is received that does not have a "guild" object.

2022-09-06 20:09 UTC, kanishkdebnath-bst commented on src/main/kotlin/gg/botlabs/oauth/OAuthApplication.kt
> +                    getJSONObject("guild").optString("id")
Changing getJSONObject to optJSONObject to get a null value for the cases when "guild" object is not present.

2022-09-08 10:51 UTC, freyacodes requested changes
Your code will still cause exceptions on line 101 and 125. In the case of 101 it is now because you're calling `optString("id")` on what is potentially a null value.

Nevertheless, I will still not accept this PR as long as you add changes specific to Discord. Please pass the JSONObject as part of TokenGrant instead of anything Discord-specific.

2022-09-08 11:41 UTC, freyacodes approved these changes

2022-09-08 11:41 UTC, merged